{% set name = "eo-learn-ml-tools" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 83386e0e0528432dde3d82fe7630c2e0daf18413e21e8987557f35eab8abdb37

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - eo-learn-core
    - matplotlib-base
    - pandas
    - python >=3.5
    - scikit-image
    - seaborn

test:
  imports:
    - eolearn
    - eolearn.ml_tools

about:
  home: https://github.com/sentinel-hub/eo-learn
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A collection of Machine Learning utilities
  doc_url: https://pypi.org/project/eo-learn-ml-tools/
  dev_url: https://github.com/sentinel-hub/eo-learn

extra:
  recipe-maintainers:
    - mxr-conda
    - mwilson8
    - dcunn
    - oblute
    - rluria14
    - benhuff
